app:
    genshin:
        region-settings:
            hk4e_cn:
                im-endpoint: "https://api-takumi.mihoyo.com"
                endpoint: "hk4e-api.mihoyo.com"
            hk4e_global:
                im-endpoint: "https://api-os-takumi.mihoyo.com"
                endpoint: "https://hk4e-api-os.mihoyo.com"
        client-read-timeout: 120000
        client-connect-timeout: 120000
        client-url: http://localhost/${server.servlet.context-path}

management:
    endpoints:
        web:
            exposure:
                include: info,health,prometheus
spring:
    jpa:
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                globally_quoted_identifiers: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mariadb://localhost:3306/genshin
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 284393890913-echi0hp3jmr62423ocp3dkkoqbuunmvi.apps.googleusercontent.com
                        client-secret: Oaf6A5FteFAV8ySZKJG9cU-h
                        redirect-uri: ${app.genshin.client-url}/login/oauth2/code/{registrationId}
                    github:
                        client-id: f1ceb56d1272dae4f8c3
                        client-secret: 8374f53cde67fe6ca154c3e9f911734b47e2744f
                        redirect-uri: ${app.genshin.client-url}/login/oauth2/code/{registrationId}
                        scope:
                            - read:user
                            - user:email
    mvc:
        throw-exception-if-no-handler-found: true
        static-path-pattern: /static/**
logging:
    level:
        org.hibernate.SQL: debug
server:
    servlet:
        context-path: /api
